name: BLOG_CI

# 在发生push事件时触发。
on: push

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps: # 步骤
      - name: Checkout # 步骤1
        uses: actions/checkout@v2 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: Install dependencies
        run: yarn install
      - name: run blog_deploy.sh # （同时部署到github或者coding）
        env: # 设置环境变量
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }} # toKen私密变量
          NODE_BUILD_ENV: github # 确定一些行为,如是否添加图片cdn
          NODE_ENV: production # 生产模式
        run: yarn deploy
